services:
  db:
    container_name: postgres-${DB_DATABASE:-shopping}
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-shopping}
      POSTGRES_USER: ${DB_USERNAME:-pguser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pgpassword}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
